# Generated by Django 2.0.3 on 2019-04-20 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('data_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('tb', models.CharField(max_length=100)),
            ],
        ),
    ]
