# Generated by Django 2.0.3 on 2019-05-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_memory_playnum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='id',
        ),
        migrations.RemoveField(
            model_name='playnum',
            name='id',
        ),
        migrations.AddField(
            model_name='memory',
            name='data_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='playnum',
            name='data_id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
    ]
