# Generated by Django 2.0.3 on 2019-05-02 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20190502_1437'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateAction',
            fields=[
                ('data_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=100)),
                ('action', models.IntegerField(default=0)),
            ],
        ),
    ]
