# Generated by Django 2.0.3 on 2019-05-02 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_stateaction_next_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stateaction',
            name='next_state',
        ),
    ]
