# Generated by Django 2.0.3 on 2019-05-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_epsilon'),
    ]

    operations = [
        migrations.CreateModel(
            name='C',
            fields=[
                ('data_id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('C', models.FloatField(default=20)),
            ],
        ),
    ]
