# Generated by Django 2.0.3 on 2019-05-10 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_c'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c',
            name='C',
            field=models.IntegerField(default=20),
        ),
    ]
